export const ROUTES = {
  LOGIN:               'Login',
  REGISTER:            'Register',
  WELCOME:             'Welcome',
  FORGOT_PASSWORD:     'ForgotPassword',
  OTP_VERIFY:          'OTPVerify',
  CHANGE_PASSWORD:     'ChangePassword',
  FINANCES:            'Finances',
  PERSONAL_FINANCES:   'PersonalFinances',
  COUPLE_FINANCES:     'CoupleFinances',
  SIMULATORS:          'Simulators',
  SIMULATOR_CDT:       'SimulatorCDT',
  SIMULATOR_DEBT:      'SimulatorDebt',
  SIMULATOR_EMERGENCY: 'SimulatorEmergency',
  SIMULATOR_SAVINGS:   'SimulatorSavings',
  SIMULATOR_PENSION:   'SimulatorPension',
  SIMULATOR_LOANS:     'SimulatorLoans',
};
