import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS } from '../../constants/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  headerEmoji: { fontSize: 28 },
  headerTitle: { flex: 1, fontSize: 20, fontWeight: '700', color: COLORS.darkGray },
  tabs: {
    flexDirection: 'row',
    paddingHorizontal: SPACING.md,
    gap: SPACING.xs,
    marginTop: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    backgroundColor: COLORS.lightYellow,
  },
  tabActive: { backgroundColor: COLORS.darkYellow },
  tabGastos: { backgroundColor: COLORS.red },
  tabText: { color: COLORS.darkGray, fontWeight: '600', fontSize: 14 },
  tabTextActive: { color: COLORS.white },
  balanceBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.offWhite,
  },
  balanceText: { fontSize: 14, fontWeight: '600', color: COLORS.darkGray },
  periodText: { fontSize: 14, color: COLORS.gray },
  scroll: { flex: 1 },
  section: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.md },
  row: { flexDirection: 'row', gap: SPACING.sm },
  categoryList: { flex: 1, gap: SPACING.xs },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.offWhite,
    borderRadius: RADIUS.sm,
    paddingVertical: 8,
    paddingHorizontal: SPACING.sm,
    gap: SPACING.xs,
  },
  catDot: { width: 10, height: 10, borderRadius: 5 },
  catLabel: { flex: 1, fontSize: 13, color: COLORS.darkGray, fontWeight: '500' },
  catEmoji: { fontSize: 16 },
  chartArea: { alignItems: 'center', justifyContent: 'flex-start', flex: 1 },
  chartLegend: { marginTop: SPACING.xs, gap: 2, alignItems: 'center' },
  legendText: { fontSize: 11, fontWeight: '600' },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.offWhite,
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
    marginTop: SPACING.sm,
  },
  totalLabel: { fontSize: 14, fontWeight: '600', color: COLORS.darkGray },
  totalValue: { fontSize: 14, fontWeight: '700' },
  resumeTitle: { fontSize: 16, fontWeight: '700', color: COLORS.darkGray, marginBottom: SPACING.xs },
  resumeRow: {
    backgroundColor: COLORS.offWhite,
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
    marginBottom: 4,
  },
  resumeLabel: { fontSize: 13, color: COLORS.darkGray },
  resumeHighlight: {
    backgroundColor: '#FFF8E0',
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.primaryYellow,
    marginTop: SPACING.xs,
  },
  resumeHighlightText: { fontSize: 13, fontWeight: '700', color: COLORS.darkGray },
  selectorHeader: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    backgroundColor: '#FFF8E0',
    paddingBottom: SPACING.xs,
  },
  selectorLabel: { fontSize: 13, fontWeight: '600', color: COLORS.darkGray },
  yearSelector: {
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    backgroundColor: '#FFF8E0',
    gap: 4,
  },
  yearText: { fontSize: 16, color: COLORS.gray },
  yearActive: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.darkGray,
    borderWidth: 1,
    borderColor: COLORS.primaryYellow,
    paddingHorizontal: SPACING.lg,
    paddingVertical: 4,
    borderRadius: RADIUS.sm,
  },
  logoArea: { alignItems: 'center', paddingVertical: SPACING.lg },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    padding: SPACING.xl,
    gap: SPACING.md,
  },
  modalTitle: { fontSize: 20, fontWeight: '700', color: COLORS.darkGray },
  modalSubtitle: { fontSize: 14, color: COLORS.gray },
  modalInput: {
    borderWidth: 2,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.darkGray,
  },
  modalBtns: { flexDirection: 'row', gap: SPACING.sm },
  modalBtn: { flex: 1, paddingVertical: 14, borderRadius: RADIUS.full, alignItems: 'center' },
  modalBtnText: { fontSize: 15, fontWeight: '600', color: COLORS.darkGray },
  balanceRight: { flexDirection: 'row', alignItems: 'center' },
  catValue: { fontSize: 11, color: COLORS.gray, fontWeight: '500', marginRight: 2 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  saveBtn: {
    backgroundColor: COLORS.darkYellow,
    borderRadius: RADIUS.full,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: SPACING.md,
  },
  saveBtnText: { fontSize: 16, fontWeight: '700', color: COLORS.white },
  saveError: { fontSize: 13, color: COLORS.red, textAlign: 'center', marginTop: SPACING.sm },
});
