import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS } from '../../constants/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  backBtn: { width: 40, alignItems: 'center' },
  backArrow: { fontSize: 32, color: COLORS.darkGreen, lineHeight: 36 },
  byline: {
    color: COLORS.gray,
    fontSize: 14,
  },
  headerTitle: { fontSize: 20, fontWeight: '700', color: COLORS.darkGray },
  content: { padding: SPACING.md, gap: SPACING.md, paddingBottom: 80 },
  description: { fontSize: 14, color: COLORS.gray, marginBottom: SPACING.xs },
  logoArea: { alignItems: 'center', paddingVertical: SPACING.lg },
  youtubeCard: {
    width: 310,
    height: 110,
    borderRadius: 16,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  spotifyCard: {
    width: 310,
    height: 110,
    borderRadius: 16,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  applePodcastCard: {
    width: 310,
    height: 110,
    borderRadius: 16,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  ytInner: {
    justifyContent: "center",
    alignItems: "center",
  },
  ytIcon: {
    width: 900,
    height: 200,
    marginBottom: 8,
  },
  ytLabel: {
    fontSize: 6,
    fontWeight: "600",
    textAlign: "center",
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.lightGray,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: COLORS.primaryGreen,
    paddingHorizontal: SPACING.md,
    height: 48,
  },
  inputRowError: {
    borderColor: COLORS.red,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: COLORS.darkGray,
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xl,
  },
  popupCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    width: '85%',
    alignItems: 'center',
    gap: SPACING.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  popupIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.darkGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.xs,
  },
  popupIconCircleError: {
    backgroundColor: COLORS.red,
  },
  popupIconText: {
    fontSize: 30,
    color: COLORS.white,
    fontWeight: '700',
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkGreen,
    textAlign: 'center',
  },
  popupTitleError: {
    color: COLORS.red,
  },
  popupMessage: {
    fontSize: 14,
    color: COLORS.darkGray,
    textAlign: 'center',
    lineHeight: 20,
  },
});
